# Imagen ligera de Python
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /app

# Como el Dockerfile está en la raíz, y el archivo está en client/, usa:
COPY sensor_client/send_lectura.py .

# Instala la dependencia necesaria
RUN pip install --no-cache-dir requests

# Ejecuta el script automáticamente al iniciar el contenedor
CMD ["python", "send_lectura.py"]

