# Imagen de Python
FROM python:3.11

# Directorio de trabajo
WORKDIR /app

# Copia de archivos
COPY sensor_client/send_lectura.py .
COPY sensor_client/requirements.txt .

# Dependencia necesaria
RUN pip install --no-cache-dir -r requirements.txt

# Ejecutar el script
CMD ["python", "send_lectura.py"]

