# Imagen
FROM python:3.11

# Directorio de trabajo
WORKDIR /app

# Copia de archivos
COPY backend/ /app/

# Dependencias
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia del backend
COPY backend/ .

# P Expone el puerto
EXPOSE 8000

# Ejecuta FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
