# Usa una imagen ligera
FROM python:3.11

# Establece directorio de trabajo
WORKDIR /app

# Copia archivos
COPY backend/ /app/

# Instala dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto
EXPOSE 8000

# Ejecuta FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
